In [18]:
import numpy as np
arr=[[1,2],[3,4]]
arr = np.array(arr)

eigenvalues, eigenvectors = np.linalg.eig(arr)
determinant = np.linalg.det(arr)

print("Eigenvalues?")
print(eigenvalues)
print("\nEigenvectors?")
print(eigenvectors)
print("\nDeterminant?")
print(determinant)

vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])

cross_product = np.cross(vec1, vec2)
print("\nCross product?")
print(cross_product)

A = np.array([[1, 2, -2],
              [2, 1, -5],
              [1, -4, 1]])
b = np.array([-15, -21, 18])
solution = np.linalg.solve(A, b)

print("\nSolution?")
print(solution)

Eigenvalues?
[-0.37228132  5.37228132]

Eigenvectors?
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Determinant?
-2.0000000000000004

Cross product?
[-3  6 -3]

Solution?
[-1. -4.  3.]
